### ISSUE TITLE
I encountered a problem when I installed it, which seemed to be a dependency

### ISSUE THREAD

**Issue by thunderstreak** [Colored-Coins/BankBox#4]
> v8-debug@0.7.7 install D:\BankBox\node_modules\electron-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@8.5.0 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "E:\Python\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\BankBox\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\BankBox\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\BankBox\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "E:\\Node\\node.exe" "D:\\BankBox\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\BankBox\\node_modules\\electron-inspector\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v57-win32-x64\\debug.node" "--module_name=debug" "--module_path=D:\\BankBox\\node_modules\\electron-inspector\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v57-win32-x64"
gyp ERR! cwd D:\BankBox\node_modules\electron-inspector\node_modules\v8-debug
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'E:\Node\node.exe D:\BankBox\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\BankBox\node_modules\electron-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v57-win32-x64\debug.node --module_name=debug --module_path=D:\BankBox\node_modules\electron-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\BankBox\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "E:\\Node\\node.exe" "D:\\BankBox\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\BankBox\node_modules\electron-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v8.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'E:\Node\node.exe D:\BankBox\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\BankBox\node_modules\electron-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v57-win32-x64\debug.node --module_name=debug --module_path=D:\BankBox\node_modules\electron-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v57-win32-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

---------------------------------------------------------------------------------
How can I fix it!

**Comment by oleiba** [comment]
Can you please specify:
- what is the action you did prior to that error (i.e. which command\installation did you use) ?
- what OS are you using?

**Comment by thunderstreak** [comment]
My windos10 x64 operating system,
First of all, I first run NPM start found the cause of the problem is the need to install the node - pre - gyp, reference on this link: https://github.com/chjj/pty.js/issues/60
The second run NPM start will also indicate that I have not found the electron, so I installed it again, and then I can run it.
Finally, I have a problem that the "importAddress" network request is wrong when I run. I want to know where I can fix it
